(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(avy-background t)
 '(backup-by-copying t)
 '(backup-directory-alist '(("." . "~/.emacs.d/backup")))
 '(before-save-hook '(delete-trailing-whitespace))
 '(blink-cursor-mode nil)
 '(column-number-mode t)
 '(custom-safe-themes
   '("246a9596178bb806c5f41e5b571546bb6e0f4bd41a9da0df5dfbca7ec6e2250c" "584c03e1f1a5d552c24b4edcf4c441654440ca86227c7807d0e609c6878d0056" default))
 '(default-frame-alist
    '((bottom-divider-width . 1)
      (ns-appearance . light)
      (ns-transparent-titlebar . t)
      (background-mode . light)
      (background-color . "#FFFFFF")))
 '(delete-old-versions t)
 '(emacs-lisp-mode-hook '(parinfer-rust-mode))
 '(feebleline-mode t nil (feebleline))
 '(font-lock-global-modes '(not speedbar-mode))
 '(frame-background-mode 'light)
 '(global-auto-revert-mode t)
 '(global-dash-fontify-mode t)
 '(global-hl-line-mode t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(ivy-mode t)
 '(ivy-prescient-mode t)
 '(kept-new-versions 20)
 '(kept-old-versions 5)
 '(lsp-eldoc-enable-hover t)
 '(lsp-enable-snippet nil)
 '(lsp-enable-symbol-highlighting nil)
 '(lsp-headerline-breadcrumb-enable nil)
 '(lsp-lens-enable t)
 '(lsp-modeline-code-actions-enable nil)
 '(lsp-modeline-diagnostics-enable nil)
 '(lsp-signature-auto-activate t)
 '(lsp-signature-render-documentation t)
 '(lsp-treemacs-sync-mode t)
 '(lsp-ui-doc-show-with-cursor nil)
 '(menu-bar-mode nil)
 '(parinfer-rust-check-before-enable nil)
 '(parinfer-rust-library "~/.emacs.d/parinfer-rust/libparinfer_rust.dylib" t)
 '(recentf-mode t)
 '(ring-bell-function 'ignore)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 100000)
 '(scroll-preserve-screen-position 1)
 '(size-indication-mode t)
 '(smartparens-global-mode t)
 '(solaire-global-mode t)
 '(tool-bar-mode nil)
 '(truncate-partial-width-windows t)
 '(winner-dont-bind-my-keys t)
 '(winner-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(message "set-faces, dummy"))
